# Generated by Django 2.2.6 on 2019-12-19 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Car',
            new_name='Information_Face',
        ),
    ]
