# Generated by Django 2.2.7 on 2019-12-30 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_ir'),
    ]

    operations = [
        migrations.CreateModel(
            name='IR2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iddata', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=100)),
                ('university', models.TextField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='IR',
        ),
    ]
